export const VERSION='optimal-rules-v1';
export const TARGETS={energy:2300,fibre:30,hydration:2000,creatine:5,sleep:[7,9]};
export const proteinTarget=lb=>Math.round(Number(lb)*.75);
export function interpolate(x,points){if(x<=points[0][0])return points[0][1];for(let i=1;i<points.length;i++){const [x1,y1]=points[i-1],[x2,y2]=points[i];if(x<=x2)return y1+(y2-y1)*(x-x1)/(x2-x1)}return points.at(-1)[1]}
export function energyScore(kcal,target=2300){const r=kcal/target;return Math.round(interpolate(r,[[0,0],[.6,25],[.8,60],[.9,85],[.95,100],[1.05,100],[1.1,85],[1.2,60],[1.4,20],[2,0]]))}
export const progressScore=(n,target)=>Math.round(Math.min(100,Math.max(0,n/target*100)));
export function geometric(parts,weights){const known=Object.keys(weights).filter(k=>Number.isFinite(parts[k]));if(!known.length)return {score:null,coverage:0,known:0,total:Object.keys(weights).length};const sum=known.reduce((s,k)=>s+weights[k],0);const score=known.some(k=>parts[k]<=0)?0:Math.round(Math.exp(known.reduce((s,k)=>s+(weights[k]/sum)*Math.log(parts[k]),0)));return {score,coverage:sum,known:known.length,total:Object.keys(weights).length}}
export function nutritionScore(parts){return geometric(parts,{energy:.35,protein:.30,fibre:.15,balance:.20})}
export function wellnessScore(parts){const result=geometric(parts,{nutrition:.45,sleep:.25,hydration:.15,training:.15});return {...result,score:['nutrition','sleep','hydration'].every(k=>Number.isFinite(parts[k]))?result.score:null,trainingIncluded:Number.isFinite(parts.training)}}
export function sleepScore(record){if(!record||!Number.isFinite(record.hours)||!Number.isFinite(record.quality)||!Number.isFinite(record.energy))return null;const duration=interpolate(record.hours,[[0,0],[4,15],[5,30],[6,50],[6.5,65],[7,78],[7.5,90],[8,100],[9,88],[10,65],[12,30],[24,0]]),quality=Math.min(5,Math.max(1,record.quality))*20,energy=Math.min(5,Math.max(1,record.energy))*20;return Math.round(Math.min(record.hours<5.5?45:100,duration*.5+quality*.2+energy*.3))}
export function status(score,hour=new Date().getHours(),complete=true){if(score==null||!complete)return ['Incomplete','neutral'];if(hour<16&&score<70)return ['Building','neutral'];if(score>=85)return ['Strongly on track','strong'];if(score>=70)return ['Good range','good'];if(score>=50)return ['Opportunity','amber'];return ['Significant shortfall','red']}
export function parseFood(text){const t=text.toLowerCase();const qty=(re,f=1)=>Number(t.match(re)?.[1]||f);const foods=[];if(/egg/.test(t)){const n=qty(/(\d+)\s*(?:scrambled\s*)?eggs?/,2);foods.push({name:'Eggs',quantity:`${n} large`,kcal:78*n,protein:6.3*n,carbs:.6*n,fat:5.3*n,fibre:0,satFat:1.6*n,sugar:.4*n,source:'Estimated',tags:['protein']})}if(/toast|bread/.test(t)){const n=qty(/(\d+)\s*(?:slices?\s*(?:of\s*)?)?(?:toast|bread)/,1);foods.push({name:'Wholemeal toast',quantity:`${n} slice${n===1?'':'s'}`,kcal:95*n,protein:4*n,carbs:17*n,fat:1.2*n,fibre:2.4*n,satFat:.2*n,sugar:1.5*n,source:'Database',tags:['wholegrain']})}if(/butter/.test(t))foods.push({name:'Butter',quantity:'10 g',kcal:74,protein:.1,carbs:.1,fat:8.2,fibre:0,satFat:5.2,sugar:.1,source:'Estimated',tags:['high-sat-fat']});if(/chicken/.test(t)){const g=qty(/(\d+)\s*g\s*(?:of\s*)?chicken/,150);foods.push({name:'Chicken breast, cooked',quantity:`${g} g`,kcal:g*1.65,protein:g*.31,carbs:0,fat:g*.036,fibre:0,satFat:g*.01,sugar:0,source:'Database',tags:['protein']})}if(/rice/.test(t)){const g=qty(/(\d+)\s*g\s*(?:cooked\s*)?(?:basmati\s*)?rice/,200);foods.push({name:'Basmati rice, cooked',quantity:`${g} g`,kcal:g*1.3,protein:g*.027,carbs:g*.28,fat:g*.003,fibre:g*.004,satFat:g*.001,sugar:0,source:'Database',tags:['carbohydrate']})}if(/olive oil/.test(t)){const ml=qty(/(\d+)\s*ml\s*(?:of\s*)?olive oil/,15);foods.push({name:'Olive oil',quantity:`${ml} ml`,kcal:ml*8.1,protein:0,carbs:0,fat:ml*.91,fibre:0,satFat:ml*.13,sugar:0,source:'Database',tags:['fat']})}if(/banana/.test(t))foods.push({name:'Banana',quantity:'1 medium',kcal:90,protein:1.1,carbs:23,fat:.3,fibre:2.6,satFat:.1,sugar:12,source:'Database',tags:['fruit']});if(!foods.length)foods.push({name:text.trim()||'Food',quantity:'1 serving',kcal:null,protein:null,carbs:null,fat:null,fibre:null,satFat:null,sugar:null,source:'Unresolved',tags:[]});return foods}
export function totals(items){return items.reduce((a,x)=>{for(const k of ['kcal','protein','carbs','fat','fibre'])if(Number.isFinite(x[k]))a[k]+=x[k];return a},{kcal:0,protein:0,carbs:0,fat:0,fibre:0})}
export function aggregateNutrition(items){const keys=['kcal','protein','carbs','fat','fibre','satFat','sugar','salt'],values={},coverage={};for(const k of keys){const known=items.filter(x=>Number.isFinite(x[k]));values[k]=known.reduce((s,x)=>s+x[k],0);coverage[k]=items.length?known.length/items.length:0;if(items.length&&!known.length)values[k]=null}return {values,coverage,resolved:items.filter(x=>['Label','Database','Saved','Estimated'].includes(x.source)).length,total:items.length}}
export function foodBalance(items){if(!items.length)return {score:null,coverage:0,assessed:0,total:5};const resolved=items.filter(x=>x.source!=='Unresolved'&&x.source!=='Needs label'&&Array.isArray(x.tags)&&x.tags.length>0);if(!resolved.length)return {score:null,coverage:0,assessed:0,total:5,parts:{}};const parts={},produce=new Set(resolved.filter(x=>x.tags.some(t=>['fruit','vegetable'].includes(t))).map(x=>x.name.toLowerCase()));parts.variety=Math.min(100,produce.size/5*100);parts.wholegrain=resolved.some(x=>x.tags.includes('wholegrain'))?100:0;parts.protein=resolved.some(x=>x.tags.includes('protein'))?100:0;const sat=items.every(x=>Number.isFinite(x.satFat))?items.reduce((s,x)=>s+x.satFat,0):null;if(sat!==null)parts.saturatedFat=sat<=30?100:Math.max(0,100-(sat-30)*5);const sugar=items.every(x=>Number.isFinite(x.freeSugar))?items.reduce((s,x)=>s+x.freeSugar,0):null;if(sugar!==null)parts.sugar=sugar<=30?100:Math.max(0,100-(sugar-30)*4);const known=Object.values(parts).filter(Number.isFinite),resolution=resolved.length/items.length;return {score:known.length?Math.round(known.reduce((s,x)=>s+x,0)/known.length):null,coverage:known.length/5*resolution,assessed:known.length,total:5,parts}}
export const lookupLocal=(query,collections={})=>{const q=String(query).trim().toLowerCase(),all=[...(collections.savedFoods||[]),...(collections.favourites||[]),...(collections.recentFoods||[]),...(collections.products||[])];return all.find(x=>x.barcode===q||x.name?.toLowerCase()===q)||null}
export async function lookupFood(query,{collections={},fetcher=globalThis.fetch}={}){const local=lookupLocal(query,collections);if(local)return {...local,lookup:'Saved'};if(!fetcher)return {status:'unresolved',query};try{const barcode=/^\d{8,14}$/.test(String(query).trim()),url=barcode?`https://world.openfoodfacts.org/api/v2/product/${query}.json`:`https://world.openfoodfacts.org/cgi/search.pl?search_terms=${encodeURIComponent(query)}&search_simple=1&action=process&json=1&page_size=5`;const r=await fetcher(url,{headers:{'User-Agent':'OPTIMAL/1.0 (private PWA)'}});if(!r.ok)return {status:'manual-required',reason:r.status===429?'rate-limit':'lookup-failed',query};const data=await r.json(),p=barcode?data.product:data.products?.[0];if(!p)return {status:'manual-required',reason:'not-found',query};const n=p.nutriments||{};return {id:p.code||crypto.randomUUID(),name:p.product_name||query,barcode:p.code||null,kcal:Number.isFinite(n['energy-kcal_100g'])?n['energy-kcal_100g']:null,protein:Number.isFinite(n.proteins_100g)?n.proteins_100g:null,carbs:Number.isFinite(n.carbohydrates_100g)?n.carbohydrates_100g:null,fat:Number.isFinite(n.fat_100g)?n.fat_100g:null,fibre:Number.isFinite(n.fiber_100g)?n.fiber_100g:null,satFat:Number.isFinite(n['saturated-fat_100g'])?n['saturated-fat_100g']:null,sugar:Number.isFinite(n.sugars_100g)?n.sugars_100g:null,salt:Number.isFinite(n.salt_100g)?n.salt_100g:null,per:'100 g',source:'Label',lookup:'Open Food Facts',license:'ODbL'} }catch{return {status:'manual-required',reason:'offline',query}}}
export function batchPortion(ingredients,yieldG,portionG){const ratio=portionG/yieldG,t=totals(ingredients);return Object.fromEntries(Object.entries(t).map(([k,v])=>[k,v*ratio]))}
export function createBatch({id=crypto.randomUUID(),name,ingredients,yieldG,estimated=true,now=new Date().toISOString()}){if(!name||!ingredients?.length||!(yieldG>0))throw Error('Batch name, ingredients and cooked yield are required');return {id,name,ingredients:structuredClone(ingredients),yieldG,estimated,version:1,createdAt:now,updatedAt:now,finished:false}}
export function consumeBatch(batch,portionG,{id=crypto.randomUUID(),date,now=new Date().toISOString()}={}){if(!(portionG>0&&portionG<=batch.yieldG))throw Error('Invalid batch portion');return {id,batchId:batch.id,batchName:batch.name,portionG,date,createdAt:now,source:'Saved',batchSnapshot:{version:batch.version,yieldG:batch.yieldG,ingredients:structuredClone(batch.ingredients),nutrition:batchPortion(batch.ingredients,batch.yieldG,portionG)}}}
export function canEdit(localDate,today){const a=new Date(`${localDate}T12:00:00`),b=new Date(`${today}T12:00:00`);return Math.round((b-a)/864e5)>=0&&Math.round((b-a)/864e5)<=1}
export function shouldCreatineRemind({hour,taken,dismissedSession}){return hour>=18&&!taken&&!dismissedSession}
export function mergeById(local,remote){const m=new Map();for(const x of [...local,...remote]){const old=m.get(x.id);if(!old||String(x.updatedAt)>String(old.updatedAt))m.set(x.id,x)}return [...m.values()]}
export function recommend({totals,targets,saved=[],recent=[],batches=[]}){const protein=Math.max(0,targets.protein-totals.protein),energy=Math.max(0,targets.energy-totals.kcal),fibre=Math.max(0,targets.fibre-totals.fibre);const pool=[...batches.filter(x=>!x.finished),...saved,...recent];const candidates=pool.filter(x=>x.nutrition||x.kcal!==undefined).map(x=>({item:x,n:x.nutrition||x,fit:Math.abs((x.nutrition?.protein??x.protein??0)-Math.min(protein,35))*3+Math.abs((x.nutrition?.kcal??x.kcal??0)-Math.min(energy,600))*.04+Math.abs((x.nutrition?.fibre??x.fibre??0)-Math.min(fibre,10))*2})).sort((a,b)=>a.fit-b.fit);if(candidates.length&&candidates[0].fit<100)return {kind:'known',item:candidates[0].item,reason:`Fits remaining ${Math.round(protein)}g protein, ${Math.round(energy)} kcal and ${Math.round(fibre)}g fibre`};if(protein<10&&energy<150&&fibre<3)return {kind:'on-track'};if(protein>35)return {kind:'generic',item:{name:'Chicken and rice bowl',portion:'150g cooked chicken · 200g cooked basmati rice · peppers',nutrition:{kcal:510,protein:52,fibre:3}}};if(fibre>10)return {kind:'generic',item:{name:'Greek yoghurt, banana and oats',portion:'200g Greek yoghurt · 1 medium banana · 40g oats',nutrition:{kcal:420,protein:25,fibre:6}}};return {kind:'generic',item:{name:'Greek yoghurt and banana',portion:'150g Greek yoghurt · 1 medium banana',nutrition:{kcal:230,protein:16,fibre:3}}}}
export function weeklyWeighInDue(entries,today){if(!entries.length)return true;const first=new Date(`${entries[0].date}T12:00:00`),now=new Date(`${today}T12:00:00`),last=new Date(`${entries.at(-1).date}T12:00:00`);return now.getDay()===first.getDay()&&(now-last)>=6.5*864e5}
export function fortnightlyReview(entries,completeDays,target=2300){if(entries.length<3||completeDays.length<10)return {action:'insufficient',reason:'Need at least three weigh-ins and ten sufficiently complete days.'};const sorted=[...entries].sort((a,b)=>a.date.localeCompare(b.date)),days=(new Date(sorted.at(-1).date)-new Date(sorted[0].date))/864e5;if(days<12)return {action:'insufficient',reason:'Less than 14 days of trend evidence.'};const weekly=(sorted.at(-1).lb-sorted[0].lb)/(days/7),avg=Math.round(completeDays.reduce((s,x)=>s+x.kcal,0)/completeDays.length);if(weekly<.15)return {action:'increase',delta:100,evidence:{weekly,avg,target}};if(weekly>.65)return {action:'decrease',delta:-100,evidence:{weekly,avg,target}};return {action:'maintain',delta:0,evidence:{weekly,avg,target}}}
export function importFormSummaries(history,existing=[]){const summaries=history.filter(x=>x.endedAt).map(x=>({id:`form:${x.id}`,source:'FORM',programmeDay:x.day+1,startedAt:x.workoutStartedAt||x.startedAt,endedAt:x.endedAt,durationMinutes:Math.max(0,Math.round((Date.parse(x.endedAt)-Date.parse(x.workoutStartedAt||x.startedAt))/60000)),endedEarly:!!x.endedEarly,exercises:x.exercises.map(e=>({id:e.id,name:e.name,completedSets:e.sets.filter(s=>!s.warmup&&s.sides.every(a=>a.done)).map(s=>s.sides.map(a=>({weight:a.weight,reps:a.reps})))})),updatedAt:x.endedAt}));return mergeById(existing,summaries)}
export function trainingScore({scheduled,summary,reachable=true,daysLate=0}){if(!reachable)return null;if(!scheduled)return 100;if(summary&&!summary.endedEarly)return 100;if(summary?.endedEarly)return 80;if(daysLate<=1)return 80;if(daysLate<=3)return 60;return 35}
