// Shared review workflow used by meals, batch recipes, recommendations and saved foods.
export const micros={vitaminA:['Vitamin A','µg',700],vitaminC:['Vitamin C','mg',40],vitaminD:['Vitamin D','µg',10],vitaminB12:['Vitamin B12','µg',1.5],folate:['Folate','µg',200],calcium:['Calcium','mg',700],iron:['Iron','mg',8.7],magnesium:['Magnesium','mg',300],potassium:['Potassium','mg',3500],zinc:['Zinc','mg',9.5]};
export const nutrients=['kcal','protein','carbs','fat','fibre','satFat','freeSugar','salt',...Object.keys(micros)];
const categories={fruit:'Fruit',vegetable:'Vegetable',wholegrain:'Wholegrain',protein:'Protein source',carbohydrate:'Other carbohydrate',fat:'Fat source',processed:'Highly processed',addedSugar:'Higher added sugar'};
export const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const E=escapeHTML;
export function sumKnown(items){const values={},coverage={};for(const k of nutrients){const known=items.filter(x=>Number.isFinite(x[k])&&x.source!=='Unresolved'&&x.source!=='Needs label');values[k]=known.length?known.reduce((s,x)=>s+x[k],0):null;coverage[k]=items.length?known.length/items.length:0}return {values,coverage}}
export const showValue=(n,u='')=>Number.isFinite(n)?`${Math.round(n*10)/10}${u}`:'Unknown'+(u?' ('+u.trim()+')':'');
export function totalText(items){const {values:v,coverage:c}=sumKnown(items);return `${showValue(v.kcal,' kcal')} · ${showValue(v.protein,'g protein')} · ${showValue(v.fibre,'g fibre')}${['kcal','protein','carbs','fat','fibre'].some(k=>c[k]<1)?' · incomplete':''}`}
export function scaleItem(item,factor){const copy=structuredClone(item);for(const k of nutrients)copy[k]=Number.isFinite(item[k])?item[k]*factor:null;copy.amount=(item.amount||item.grams||100)*factor;if(Number.isFinite(item.grams))copy.grams=item.grams*factor;copy.quantity=`${Math.round(copy.amount*10)/10} ${item.unit||'g'}`;return copy}
function normalizeOFF(p){const n=p.nutriments||{},fields={kcal:'energy-kcal',protein:'proteins',carbs:'carbohydrates',fat:'fat',fibre:'fiber',satFat:'saturated-fat',salt:'salt',vitaminA:'vitamin-a',vitaminC:'vitamin-c',vitaminD:'vitamin-d',vitaminB12:'vitamin-b12',folate:'folates',calcium:'calcium',iron:'iron',magnesium:'magnesium',potassium:'potassium',zinc:'zinc'},x={id:'off:'+p.code,barcode:p.code,name:p.product_name||'Unnamed product',brand:p.brands||'',package:p.quantity||'',serving:p.serving_size||'',source:'Open Food Facts',basis:100,basisUnit:'g',tags:null};for(const [k,key]of Object.entries(fields)){const value=n[key+'_100g'];x[k]=Number.isFinite(value)?value*(micros[k]?(micros[k][1]==='µg'?1e6:1e3):1):null}return x}
let catalogPromise,lastSearch=0;
export function cofid(){return catalogPromise??=fetch('./cofid.json').then(r=>{if(!r.ok)throw Error('Offline food database unavailable');return r.json()})}
const terms=q=>q.toLowerCase().replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(Boolean);
export async function searchFoods(query,db,remote=true){const q=terms(query),saved=[...(db.products||[]),...(db.saved||[]),...(db.favourites||[]),...(db.recents||[])].filter(x=>!x.deletedAt&&x.name&&(!q.length||q.every(t=>`${x.name} ${x.brand||''}`.toLowerCase().includes(t)))),generic=(await cofid()).filter(x=>q.length&&q.every(t=>x.name.toLowerCase().includes(t))).slice(0,30);let products=[],error='';if(remote&&navigator.onLine&&query.trim()){if(Date.now()-lastSearch<6100)error='Please wait a few seconds before another product search. Generic and saved results are available.';else{lastSearch=Date.now();try{const url='https://world.openfoodfacts.org/cgi/search.pl?search_terms='+encodeURIComponent(query)+'&search_simple=1&action=process&json=1&page_size=12';const r=await fetch(url,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error(r.status===429?'Product search rate limit reached':'Product search unavailable');products=(await r.json()).products?.map(normalizeOFF)||[];products.sort((a,b)=>q.filter(t=>b.brand.toLowerCase().includes(t)).length-q.filter(t=>a.brand.toLowerCase().includes(t)).length)}catch(e){error=e.message}}}const seen=new Set(),results=[...saved,...products,...generic].filter(x=>{const id=x.barcode||x.id||x.name;if(seen.has(id))return false;seen.add(id);return true});return {results,error}}
export async function barcodeFood(code,db){const found=[...(db.products||[]),...(db.saved||[]),...(db.favourites||[])].find(x=>!x.deletedAt&&x.barcode===code);if(found)return found;const r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(code)}.json`,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error(r.status===429?'Rate limit reached':'Product lookup unavailable');const data=await r.json();if(!data.product)throw Error('Product not found');return normalizeOFF(data.product)}
export function createFoodFlows({getDB,sheet,save,canWrite,onScan,notify}){
 const el=s=>document.querySelector(s),click=(s,fn)=>el(s)?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();fn(e)}),clone=x=>structuredClone(x);
 let activeDraft=null;
 function productEditor(product={},done,back,projection=[]){const p=clone(product),basis=p.basis||100;sheet(`<h2>${p.name?'Review ingredient':'Enter label'}</h2><form id="ingredient-form"><label class="field">Food name<input name="name" required value="${E(p.name)}"></label><p class="coverage">${E(p.brand||'')} · ${E(p.source||'Product label')} · values per ${basis} ${E(p.basisUnit||'g')}${p.originalQuantity?' · original amount: '+E(p.originalQuantity):''}</p><label class="field">Nutrition basis unit<select name="basisUnit"><option value="g">per ${basis} g</option><option value="ml">per ${basis} ml</option>${p.basisUnit==='original serving'?'<option value="original serving">per original logged serving</option>':''}</select></label><label class="field">Consumed amount<input name="amount" required type="number" min="0.1" max="10000" step="any" value="${p.amount??''}" placeholder="Enter quantity"></label><label class="field">Unit<select name="unit">${p.basisUnit==='original serving'?'<option value="original serving">original logged servings</option>':''}<option value="g">g</option><option value="ml">ml</option><option value="portion">portions</option><option value="package">packages</option></select></label><label class="field">Grams or ml per portion / package<input name="portionSize" type="number" min="0.1" step="any" value="${p.portionSize||''}" placeholder="Required for portions or packages"></label><details open><summary>Nutrition per ${basis}${E(p.basisUnit||'g')}</summary>${['kcal','protein','carbs','fat','fibre','satFat','freeSugar','salt'].map(k=>inputNutrient(k,p)).join('')}</details><details><summary>Micronutrients (optional)</summary>${Object.keys(micros).map(k=>inputNutrient(k,p)).join('')}</details><fieldset><legend>Food categories · confirm or correct</legend>${Object.entries(categories).map(([k,v])=>`<label class="toggle"><input name="category" type="checkbox" value="${k}" ${p.tags?.includes(k)?'checked':''}>${v}</label>`).join('')}<label class="toggle"><input name="categoryKnown" type="checkbox" ${Array.isArray(p.tags)?'checked':''}>I have checked the categories (none may apply)</label></fieldset><label class="toggle"><input name="favourite" type="checkbox" ${p.favourite?'checked':''}>Favourite this food</label><label class="toggle"><input name="saveFood" type="checkbox">Save food for reuse</label><p id="ingredient-projected" role="status"></p><p id="ingredient-total" role="status"></p><button class="primary">Use ingredient</button><button type="button" class="secondary" id="ingredient-back">Back</button></form>`);
 const form=el('#ingredient-form');form.elements.unit.value=p.unit||'g';form.elements.basisUnit.value=p.basisUnit||'g';let corrected=false;form.querySelectorAll('[data-nutrient]').forEach(x=>x.addEventListener('input',()=>corrected=true));const read=()=>{const f=new FormData(form),unit=f.get('unit'),amount=Number(f.get('amount')),portion=Number(f.get('portionSize')),basisUnit=f.get('basisUnit'),mass=['portion','package'].includes(unit)?amount*portion:unit===basisUnit?amount:NaN,definition={...p,name:f.get('name'),id:p.id||crypto.randomUUID(),basis,basisUnit,portionSize:portion||null,tags:f.has('categoryKnown')||f.getAll('category').length?f.getAll('category'):null,source:corrected?'Corrected by you':p.source||'Product label'};for(const k of nutrients){const raw=f.get(k);definition[k]=raw!==null&&raw!==''?Number(raw):null}const item={...definition,definition:clone(definition),amount,unit,quantity:`${amount} ${unit}`,grams:p.basisUnit==='original serving'?null:mass};for(const k of nutrients)item[k]=Number.isFinite(definition[k])?definition[k]*mass/basis:null;return {item,definition,f,mass}};
 form.addEventListener('input',()=>{const {item}=read();el('#ingredient-total').textContent=totalText([item]);if(projection.length)el('#ingredient-projected').textContent='Projected daily totals: '+totalText([...projection,item])});form.addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation();const {item,definition,f,mass}=read();if(!(mass>0&&Number.isFinite(mass))){notify('Match the amount unit to the nutrition basis, or enter the weight/volume of a portion or package.');return}const db=getDB();definition.updatedAt=new Date().toISOString();db.products=db.products||[];const index=db.products.findIndex(x=>definition.barcode?x.barcode===definition.barcode:x.id===definition.id);if(index<0)db.products.push(definition);else db.products[index]=definition;if(f.has('favourite')){db.favourites=db.favourites||[];db.favourites=[...db.favourites.filter(x=>x.id!==definition.id),clone(definition)]}if(f.has('saveFood')){db.saved=db.saved||[];db.saved=[...db.saved.filter(x=>x.id!==definition.id),clone(definition)]}done(item)});click('#ingredient-back',()=>back?.());
 }
 function inputNutrient(k,p){return `<label class="field">${micros[k]?micros[k][0]+' ('+micros[k][1]+')':k==='kcal'?'Energy (kcal)':k+' (g)'}<input name="${k}" data-nutrient="${k}" type="number" min="0" step="any" value="${Number.isFinite(p[k])?p[k]:''}" placeholder="Unknown"></label>`}
 function picker(done,back,query=''){sheet(`<h2>Choose food</h2><form id="find-food"><label class="field">Product or generic food<input name="query" value="${E(query)}" placeholder="Chicken breast"></label><button class="primary">Search</button></form><div class="flow-actions"><button id="generic-only">Offline generic search</button><button id="pick-scan">Scan barcode</button><button id="pick-label">Enter label</button></div><p id="search-status" role="status"></p><div id="search-results" class="pick-list"></div><button class="secondary" id="pick-back">Back</button>`);const run=async remote=>{const q=el('#find-food input').value;el('#search-status').textContent='Searching…';try{const {results,error}=await searchFoods(q,getDB(),remote);if(!el('#search-results'))return;el('#search-status').textContent=error||`${results.length} matches · choose the food you ate`;el('#search-results').innerHTML=results.map((x,i)=>`<button type="button" data-result="${i}"><strong>${E(x.name)}</strong><span>${E(x.brand||'')} ${E(x.package||x.serving||'')} · ${E(x.barcode||'')} · ${E(x.source)} · ${nutrients.slice(0,5).filter(k=>Number.isFinite(x[k])).length}/5 nutrients</span></button>`).join('');el('#search-results').querySelectorAll('button').forEach(b=>b.onclick=e=>{e.stopImmediatePropagation();productEditor(results[+b.dataset.result],done,()=>picker(done,back,q))})}catch(e){el('#search-status').textContent=e.message+' · Enter label is available.'}};el('#find-food').onsubmit=e=>{e.preventDefault();run(true)};click('#generic-only',()=>run(false));click('#pick-label',()=>productEditor({},done,()=>picker(done,back)));click('#pick-scan',()=>onScan(x=>productEditor(x,done,()=>picker(done,back))));click('#pick-back',()=>back?.());if(query)run(false)}
 function review(draft,onDone){activeDraft=draft;sheet(`<h2>${draft.batch?'Review batch':draft.recommendation?'Review recommendation':'Review meal'}</h2><div class="flow-progress" aria-label="Meal progress"><span>Ingredients</span><span aria-hidden="true">/</span><b>Review</b><span aria-hidden="true">/</span><span>Save</span></div><label class="field">Name<input id="draft-name" value="${E(draft.name||'Meal')}"></label>${!draft.batch?`<label class="field">Meal type<select id="draft-type">${['Food','Snack','Breakfast','Lunch','Dinner'].map(x=>`<option ${draft.type===x?'selected':''}>${x}</option>`).join('')}</select></label>`:''}<div class="pick-list">${draft.items.map((x,i)=>`<div class="review-item"><strong>${E(x.name)}</strong><p>${E(x.quantity||'Quantity needed')} · ${totalText([x])} · ${E(x.source||'Unknown')}</p><button data-edit-ingredient="${i}">Change quantity / values</button><button data-replace-ingredient="${i}">Choose another food</button><button data-remove-ingredient="${i}">Remove</button></div>`).join('')}</div><button class="secondary" id="draft-add">Add ingredient</button><button class="secondary" id="draft-describe">Describe ingredients</button><p id="draft-total" role="status">${totalText(draft.items)}</p>${draft.recommendation?`<p class="coverage">Projected totals: ${totalText([...(draft.currentItems||[]),...draft.items])}</p>`:''}${draft.batch?`<label class="field">Estimated cooked yield (g)<input id="draft-yield" type="number" min="1" step="any" value="${draft.yieldG||Math.round(draft.items.reduce((s,x)=>s+(x.grams||x.amount||0),0)*.9)||''}"></label><p class="coverage">Estimated from ingredient weights and 10% cooking loss. Water absorption varies; adjust this estimate.</p>`:'<label class="toggle"><input id="save-meal" type="checkbox">Save complete meal for reuse</label>'}<button class="primary" id="draft-save">${draft.batch?'Save batch':'Save as consumed'}</button><button class="secondary" id="draft-note">Save deliberately incomplete ${draft.batch?'batch':'note'}</button><button class="secondary close">Cancel</button>`);
 const capture=()=>{draft.name=el('#draft-name')?.value||draft.name;draft.type=el('#draft-type')?.value||draft.type;if(draft.batch)draft.yieldG=+el('#draft-yield').value};
 el('#draft-name').oninput=capture;if(el('#draft-type'))el('#draft-type').onchange=capture;if(el('#draft-yield'))el('#draft-yield').oninput=capture;
 el('.panel').querySelectorAll('[data-edit-ingredient]').forEach(b=>b.onclick=e=>{e.stopImmediatePropagation();capture();const i=+b.dataset.editIngredient,x=draft.items[i],definition=x.definition||(x.grams||x.amount?{...x,basis:x.grams||x.amount}:{...x,basis:1,basisUnit:'original serving',unit:'original serving',originalQuantity:x.quantity});productEditor({...definition,amount:x.amount||x.grams||(definition.basisUnit==='original serving'?1:null),unit:x.unit||definition.unit||'g'},item=>{draft.items[i]=item;review(draft,onDone)},()=>review(draft,onDone),draft.recommendation?[...(draft.currentItems||[]),...draft.items.filter((_,index)=>index!==i)]:[])});
 el('.panel').querySelectorAll('[data-replace-ingredient]').forEach(b=>b.onclick=e=>{e.stopImmediatePropagation();capture();const i=+b.dataset.replaceIngredient;picker(item=>{draft.items[i]=item;review(draft,onDone)},()=>review(draft,onDone),draft.items[i].name)});
 el('.panel').querySelectorAll('[data-remove-ingredient]').forEach(b=>b.onclick=e=>{e.stopImmediatePropagation();capture();draft.items.splice(+b.dataset.removeIngredient,1);review(draft,onDone)});click('#draft-add',()=>{capture();picker(item=>{draft.items.push(item);review(draft,onDone)},()=>review(draft,onDone))});click('#draft-describe',()=>{capture();describe('Food',value=>{draft.items.push(...value.items);review(draft,onDone)})});
 const commit=deliberate=>{capture();if(!canWrite()&&!draft.batch)return notify('Older dates are read-only.');if(!draft.items.length)return notify('Add at least one ingredient.');const unresolved=draft.items.some(x=>!Number.isFinite(x.kcal)||!Number.isFinite(x.protein)||!x.quantity);if(unresolved&&!deliberate)return notify('Review unresolved ingredients, or explicitly save an incomplete note.');if(draft.batch&&!(draft.yieldG>0))return notify('Enter the estimated cooked yield.');draft.incomplete=draft.items.some(x=>['kcal','protein','carbs','fat','fibre'].some(k=>!Number.isFinite(x[k])));draft.savedMeal=!!el('#save-meal')?.checked;onDone(clone(draft));};click('#draft-save',()=>commit(false));click('#draft-note',()=>commit(true));
 }
 function describe(type,done){sheet(`<h2>Describe meal</h2><form id="describe-form"><label class="field">What did you have?<textarea name="description" required placeholder="Chicken breast, oven chips and steamed vegetables"></textarea></label><p class="coverage">Separate ingredients with commas or “and”. You will choose matches and quantities next.</p><button class="primary">Review ingredients</button></form><button class="secondary close">Cancel</button>`);el('#describe-form').onsubmit=e=>{e.preventDefault();const description=new FormData(e.target).get('description'),parts=description.split(/,|;|\band\b/ig).map(x=>x.trim()).filter(Boolean);review({name:description,type,items:parts.map(name=>({name,source:'Unresolved',quantity:null,...Object.fromEntries(nutrients.map(k=>[k,null]))}))},done)}}
 function library(done){const db=getDB(),collections={Recent:db.recents,Favourites:db.favourites,'Saved foods':db.saved,'Saved meals':db.savedMeals,'Corrected products':db.products};sheet(`<h2>Saved and recent</h2><label class="field">Filter<input id="library-query" type="search"></label><select id="library-section" aria-label="Collection">${Object.keys(collections).map(k=>`<option>${k}</option>`).join('')}</select><div id="library-items" class="pick-list"></div><button class="secondary close">Close</button>`);const draw=()=>{const list=collections[el('#library-section').value]||[],seen=new Set(),q=el('#library-query').value.toLowerCase();const selected=list.filter(x=>{const key=x.barcode||x.id||x.name||x.text;if(seen.has(key)||x.deletedAt||!(x.name||x.text||'').toLowerCase().includes(q))return false;seen.add(key);return true});el('#library-items').innerHTML=selected.map((x,i)=>`<div class="review-item"><strong>${E(x.name||x.text)}</strong><button data-repeat="${i}">Repeat</button><button data-library-edit="${i}">Edit</button><button data-favourite="${i}">${db.favourites.some(y=>y.id===x.id&&!y.deletedAt)?'Unfavourite':'Favourite'}</button><button data-library-remove="${i}">Remove</button></div>`).join('')||'<p class="coverage">No items in this collection.</p>';el('#library-items').onclick=e=>{const b=e.target.closest('button');if(!b)return;e.stopImmediatePropagation();const i=Number(Object.values(b.dataset)[0]),x=selected[i];if(b.hasAttribute('data-repeat')){if(x.items)review({name:x.name||x.text,type:'Food',items:clone(x.items)},done);else productEditor(x,item=>review({name:item.name,type:'Food',items:[item]},done),()=>library(done))}else if(b.hasAttribute('data-library-edit')){if(x.items)review({name:x.name||x.text,type:'Food',items:clone(x.items)},d=>{Object.assign(x,{items:d.items,name:d.name,updatedAt:new Date().toISOString()});save();library(done)});else productEditor(x,item=>{Object.assign(x,item.definition,{updatedAt:new Date().toISOString()});save();library(done)},()=>library(done))}else if(b.hasAttribute('data-favourite')){const fav=db.favourites.find(y=>y.id===x.id&&!y.deletedAt);if(fav){fav.deletedAt=new Date().toISOString();fav.updatedAt=fav.deletedAt}else{const copy=clone(x);delete copy.deletedAt;copy.updatedAt=new Date().toISOString();db.favourites=[...db.favourites.filter(y=>y.id!==x.id),copy]}save();library(done)}else if(confirm('Remove this saved item? Logged meals are unchanged.')){x.deletedAt=new Date().toISOString();x.updatedAt=x.deletedAt;save();library(done)}}};el('#library-query').oninput=draw;el('#library-section').onchange=draw;draw()}
 function barcodeServing(product,done,back){
  if(!product.name)return productEditor(product,done,back);
  const p=clone(product),match=(p.package||'').trim().match(/^([\d.]+)\s*(kg|g)$/i),pack=match?+match[1]*(match[2].toLowerCase()==='kg'?1000:1):null;
  sheet(`<h2>${E(p.name)}</h2><p>${E(p.brand||'')} · ${E(p.package||'Pack weight unavailable')}</p><form id="barcode-serving"><label class="toggle"><input type="checkbox" id="whole-product">I consumed the whole product</label><label class="field" id="barcode-weight-label"><span id="barcode-weight-title">Portion consumed (g)</span><input name="amount" type="number" min="0.1" max="10000" step="any" required inputmode="decimal"></label><p id="barcode-total" role="status">Choose whole product or enter your portion weight.</p><button class="primary">Save as consumed</button></form><button class="secondary" id="barcode-correct">Edit nutrition / label</button><button class="secondary close">Cancel</button>`);
  const form=el('#barcode-serving'),whole=el('#whole-product'),amount=form.elements.amount;
  const item=()=>{const grams=whole.checked&&pack?pack:+amount.value,definition=clone(p),result={...p,definition,amount:grams,grams,unit:'g',quantity:`${grams} g`};for(const k of nutrients)result[k]=Number.isFinite(p[k])?p[k]*grams/(p.basis||100):null;return result};
  const update=()=>{el('#barcode-weight-label').hidden=whole.checked&&!!pack;amount.required=!(whole.checked&&pack);el('#barcode-weight-title').textContent=whole.checked?'Whole product weight (g)':'Portion consumed (g)';el('#barcode-total').textContent=totalText([item()])};
  whole.onchange=update;amount.oninput=update;
  form.onsubmit=e=>{e.preventDefault();e.stopImmediatePropagation();if(!canWrite())return notify('Older dates are read-only.');const value=item();if(!(value.grams>0&&value.grams<=10000))return notify('Enter the consumed weight in grams.');if(!Number.isFinite(value.kcal)||!Number.isFinite(value.protein))return notify('Nutrition is incomplete. Use Edit nutrition / label before saving.');const db=getDB();db.products=db.products||[];const i=db.products.findIndex(x=>x.barcode===p.barcode);if(i<0)db.products.push(p);else db.products[i]=p;done(value)};
  click('#barcode-correct',()=>productEditor(p,done,()=>barcodeServing(p,done,back)));
 }
 return {picker,productEditor,barcodeServing,review,describe,library};
}
